### ISSUE TITLE
bert model conversion 

### ISSUE THREAD

**Issue by Liquor520** [yiling2018/saem#6]
When I use tensorFlow's pre-trained model for conversion, I get the following error when loading the model:

/ home/hulijuan/anaconda3 / envs/torchenv/bin/python3.6 / media/hulijuan/hdisk1 / saem/train py

Namespace(batch_size=64, bert_path='./uncased_L-12_H-768_A-12/', data_name='f30k_precomp', data_path='./data/', Embed_size =1024, final_DIMS =256, grad_clip=2.0, IMG_DIM =2048, LEARning_rate =0.0001, log_step=10, embed_size=1024, final_DIMS =256, grad_clip=2.0, IMg_DIM =2048, Learning_rate =0.0001, log_step=10, Logger_name ='./runs/runX/log', lr_update=10, margin=0.2, max_violation=True, max_words=32, model_name='./runs/runX/checkpoint', num_epochs=30, resume='', trans_cfg='t_cfg.json', txt_stru='cnn', val_step=1000, word_dim=300, workers=10)

Traceback (most recent call last):

File "/media/hulijuan/hdisk1/saem/train.py", line 273, in

main()

File "/media/hulijuan/hdisk1/saem/train.py", line 93, in main

model = SAEM(opt)

File "/media/hulijuan/hdisk1/saem/model.py", line 40, in __init__

self.txt_enc = text_net.BertMapping(opt)

File "/media/hulijuan/hdisk1/saem/text_net.py", line 30, in __init__

self.bert.load_state_dict(torch.load(opt.init_checkpoint, map_location='cpu'))

The File "/ home/hulijuan/anaconda3 / envs/torchenv/lib/python3.6 / site - packages/torch/nn/modules/module. Py", line 1483, in load_state_dict

self.__class__.__name__, "\n\t".join(error_msgs)))

RuntimeError: Error(s) in loading state_dict for BertModel:

Missing key(s) in state_dict: "embeddings.word_embeddings.weight", "embeddings.position_embeddings.weight", "embeddings.token_type_embeddings.weight", "embeddings.LayerNorm.gamma", "embeddings.LayerNorm.beta", "encoder.layer.0.attention.self.query.weight", "encoder.layer.0.attention.self.query.bias", "encoder.layer.0.attention.self.key.weight", "encoder.layer.0.attention.self.key.bias", "encoder.layer.0.attention.self.value.weight", "encoder.layer.0.attention.self.value.bias", "encoder.layer.0.attention.output.dense.weight", "encoder.layer.0.attention.output.dense.bias", "encoder.layer.0.attention.output.LayerNorm.gamma"

Unexpected key(s) in state_dict: "bert.embeddings.word_embeddings.weight", "bert.embeddings.position_embeddings.weight", "bert.embeddings.token_type_embeddings.weight", "bert.embeddings.LayerNorm.weight", "bert.embeddings.LayerNorm.bias", "bert.encoder.layer.0.attention.self.query.weight", "bert.encoder.layer.0.attention.self.query.bias", "bert.encoder.layer.0.attention.self.key.weight", "bert.encoder.layer.0.attention.self.key.bias", "bert.encoder.layer.0.attention.self.value.weight", "bert.encoder.layer.0.attention.self.value.bias", "bert.encoder.layer.0.attention.output.dense.weight", "bert.encoder.layer.0.attention.output.dense.bias", "bert.encoder.layer.0.attention.output.LayerNorm.weight",

Could you tell me the reason, please?

Is it the Tensorflow version? Or I wonder if you can directly upload the converted pre-training model ~

Looking forward to your reply!

**Comment by Anu-orange** [comment]
Hello, I have the same problem as you, how did you solve it in the end? Can you tell me？thank you

**Comment by Anu-orange** [comment]
> When I use tensorFlow's pre-trained model for conversion, I get the following error when loading the model:
> 
> / home/hulijuan/anaconda3 / envs/torchenv/bin/python3.6 / media/hulijuan/hdisk1 / saem/train py
> 
> Namespace(batch_size=64, bert_path='./uncased_L-12_H-768_A-12/', data_name='f30k_precomp', data_path='./data/', Embed_size =1024, final_DIMS =256, grad_clip=2.0, IMG_DIM =2048, LEARning_rate =0.0001, log_step=10, embed_size=1024, final_DIMS =256, grad_clip=2.0, IMg_DIM =2048, Learning_rate =0.0001, log_step=10, Logger_name ='./runs/runX/log', lr_update=10, margin=0.2, max_violation=True, max_words=32, model_name='./runs/runX/checkpoint', num_epochs=30, resume='', trans_cfg='t_cfg.json', txt_stru='cnn', val_step=1000, word_dim=300, workers=10)
> 
> Traceback (most recent call last):
> 
> File "/media/hulijuan/hdisk1/saem/train.py", line 273, in
> 
> main()
> 
> File "/media/hulijuan/hdisk1/saem/train.py", line 93, in main
> 
> model = SAEM(opt)
> 
> File "/media/hulijuan/hdisk1/saem/model.py", line 40, in **init**
> 
> self.txt_enc = text_net.BertMapping(opt)
> 
> File "/media/hulijuan/hdisk1/saem/text_net.py", line 30, in **init**
> 
> self.bert.load_state_dict(torch.load(opt.init_checkpoint, map_location='cpu'))
> 
> The File "/ home/hulijuan/anaconda3 / envs/torchenv/lib/python3.6 / site - packages/torch/nn/modules/module. Py", line 1483, in load_state_dict
> 
> self.**class**.**name**, "\n\t".join(error_msgs)))
> 
> RuntimeError: Error(s) in loading state_dict for BertModel:
> 
> Missing key(s) in state_dict: "embeddings.word_embeddings.weight", "embeddings.position_embeddings.weight", "embeddings.token_type_embeddings.weight", "embeddings.LayerNorm.gamma", "embeddings.LayerNorm.beta", "encoder.layer.0.attention.self.query.weight", "encoder.layer.0.attention.self.query.bias", "encoder.layer.0.attention.self.key.weight", "encoder.layer.0.attention.self.key.bias", "encoder.layer.0.attention.self.value.weight", "encoder.layer.0.attention.self.value.bias", "encoder.layer.0.attention.output.dense.weight", "encoder.layer.0.attention.output.dense.bias", "encoder.layer.0.attention.output.LayerNorm.gamma"
> 
> Unexpected key(s) in state_dict: "bert.embeddings.word_embeddings.weight", "bert.embeddings.position_embeddings.weight", "bert.embeddings.token_type_embeddings.weight", "bert.embeddings.LayerNorm.weight", "bert.embeddings.LayerNorm.bias", "bert.encoder.layer.0.attention.self.query.weight", "bert.encoder.layer.0.attention.self.query.bias", "bert.encoder.layer.0.attention.self.key.weight", "bert.encoder.layer.0.attention.self.key.bias", "bert.encoder.layer.0.attention.self.value.weight", "bert.encoder.layer.0.attention.self.value.bias", "bert.encoder.layer.0.attention.output.dense.weight", "bert.encoder.layer.0.attention.output.dense.bias", "bert.encoder.layer.0.attention.output.LayerNorm.weight",
> 
> Could you tell me the reason, please?
> 
> Is it the Tensorflow version? Or I wonder if you can directly upload the converted pre-training model ~
> 
> Looking forward to your reply!

Hello, I have the same problem as you, how did you solve it in the end? Can you tell me？thank you
